# Generated by Django 3.1.2 on 2020-10-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalleryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
